### ISSUE TITLE
ARPAV - test 1 20/01/2022

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#1] opened 2022-01-21 15:19 UTC
bugs / to be check
-----------------------------------------------------------------------------------------------------------------------

    • different browsers (Firefox vs. Chrome) are rendering the web pages not entirely correct: in particular check for the initial input form where the date fields appear to be much "shorter" than needed (i.e. there is not enough "space" to see what is effectively input by the user)
    • in "Partners", it appears that the form is not saving (retaining) the eventual change of the coordinator; the same apply sometimes for the field "country", but not in a clear and reproducible way;

new additional features needed / proposed for further evaluation
------------------------------------------------------------------------------------------------------------------------
    • a button "apply" to save the modifications at a fixed point in time;
    • provide an additional split of the total estimation of CF into the different "categories": "equipment", "events", "printable deliverables";
    • provide a short user's manual and/or insert a cross reference to the paragraph of the official methodology documentation for each of the field to be input on the form;

proposed modifications and enhancements
-----------------------------------------------------------------------------------------------------------------------
    • in "Partners" change "seasonal employees" to "part-time employees", if that is effectively supposed to be the original intent (to be check);
    • in "Events" modify as follows: "On-site" -> "In presence", "Virtual" ->"On-line", "Hybrid" -> "Mixed mode: both in presence and on-line" in order to be more comprehensive for the final user
    • specify somewhere in the form that the accounting of events is supposed to be referred for the whole project partners and not for the single partner as occurred in the upper tab “Staff” (to avoid possible misinterpretations);
    • a major simplification of the "printable deliverables" is needed, reducing the number of categories; choose and group categories in terms of the relative emission factors (which is it probably a function of the paper dimension?), evaluate the possibility to simplify the form by just input the bulk number of pages for total printable deliverables; in other words, in our opinion the logic behind this tab is to start from the available emission factors and disaggregate the type of deliverable accordingly, not splitting different categories with the same emission factors
    • in “Equipment” a substantial revision is needed in terms of a more clear specification of the relative categories (vehicles? machines? Furnitures?); the detail about the weight for each item appears to be very difficult to find for the final user (therefore it seems to be a useless overhead): possibly simplify the form in terms of numbers of equipment for each category (and here again, the definition of the equipment categories should be related to the available emission factors);

minor issues
-----------------------------------------------------------------------------------------------------------------------
- errata: "carbon dioxyde emited", corrige: "carbon dioxide emitted"

**Comment by MaToSan24** [comment] 2022-01-27 01:05
### Solved issues / Implemented suggestions
• different browsers (Firefox vs. Chrome) are rendering the web pages not entirely correct: in particular check for the initial input form where the date fields appear to be much "shorter" than needed (i.e. there is not enough "space" to see what is effectively input by the user)
• provide an additional split of the total estimation of CF into the different "categories": "equipment", "events", "printable deliverables";
• in "Partners" change "seasonal employees" to "part-time employees", if that is effectively supposed to be the original intent (to be check);
• in "Events" modify as follows: "On-site" -> "In presence", "Virtual" ->"On-line", "Hybrid" -> "Mixed mode: both in presence and on-line" in order to be more comprehensive for the final user
• specify somewhere in the form that the accounting of events is supposed to be referred for the whole project partners and not for the single partner as occurred in the upper tab “Staff” (to avoid possible misinterpretations);
• errata: "carbon dioxyde emited", corrige: "carbon dioxide emitted"

### Work in progress issues
• in "Partners", it appears that the form is not saving (retaining) the eventual change of the coordinator; the same apply sometimes for the field "country", but not in a clear and reproducible way;
• a button "apply" to save the modifications at a fixed point in time;
• provide a short user's manual and/or insert a cross reference to the paragraph of the official methodology documentation for each of the field to be input on the form;

**Once the "save" button is implemented, this functionality will fix the problem with the tables where, in some cases, they are not updated correctly and so, some data is missed. Also, the user manual will be referenced once the application reaches its final state, but not sooner.**

**As soon as the "save" button is implemented, all these functionalities will be released on the web app so you can keep testing the tool.**

### Pending validation
• a major simplification of the "printable deliverables" is needed, reducing the number of categories; choose and group categories in terms of the relative emission factors (which is it probably a function of the paper dimension?), evaluate the possibility to simplify the form by just input the bulk number of pages for total printable deliverables; in other words, in our opinion the logic behind this tab is to start from the available emission factors and disaggregate the type of deliverable accordingly, not splitting different categories with the same emission factors
• in “Equipment” a substantial revision is needed in terms of a more clear specification of the relative categories (vehicles? machines? Furnitures?); the detail about the weight for each item appears to be very difficult to find for the final user (therefore it seems to be a useless overhead): possibly simplify the form in terms of numbers of equipment for each category (and here again, the definition of the equipment categories should be related to the available emission factors);

**We need the methodology to be clearly defined on this section in order to implement it, so, as soon as we receive the definitive version of what should be implemented and how, we will start working on it.**

**Comment by ARPAV2022** [comment] 2022-02-01 10:41
Dear USE team,

concerning the two topics under "Pending Validation" please refer to the email sent on January 27th with the AUTH's methodological suggestions. Please, notify us once the updated release of the "simple use" tool is ready for the data entry. Thank in advance Giacomo on behalf of ARPAV

**Closed as completed** 2022-05-13 09:38 UTC
Labels: needs-triage
